version: "3.3"

networks:
  reverse-proxy-network:
    external:
      name: reverse-proxy-network

services:
  web:
    container_name: autocomplete
    build:
      context: .
      dockerfile: Dockerfile
      # ports:
      #   - "8080:8080"
    environment:
      NODE_ENV: production
    networks:
      - reverse-proxy-network
